# This is a basic workflow to help you get started with Actions

name: Second workflow

env:
  msg: "Hello from env var"
  var_name: 80

# Controls when the workflow will run
on:
  push:
    branches: [ "dev" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  Job1:
    
    # The type of runner that the job will run on
    # runs-on: self-hosted
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo $var_name

      - name: Use of secrets
        run: echo ${{ secrets.Password }}

  run_python_script:
    needs: Job1
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v3
        with:
          python-version: '3.7'

      - name: Run python script
        run: python b.py
